services:
  mongodb:
    image: mongo:latest
    container_name: mongoose-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=graeyy
      - MONGO_INITDB_ROOT_PASSWORD=falcon@568
      - MONGO_INITDB_DATABASE=testdb
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db

  node-app:
    build: .
    container_name: node-app
    restart: always
    environment:
      - MONGO_URI=mongodb://graeyy:falcon@568@mongodb:27017/testdb
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: "npm start"

networks:
  default:
    driver: bridge
