services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6378:6379"
    networks:
      - redis-network
    restart: always

networks:
  redis-network:
    driver: bridge
